import pandas as pd
from config import RATING_METRICS, EXCEL_EXPORT_FILENAME

def save_analysis_report(analysis_result, filename="review_analysis_report.txt"):
    """Save the GPT-4 analysis to a text file"""
    try:
        with open(filename, 'w', encoding='utf-8') as f:
            f.write("CUSTOMER REVIEW ANALYSIS REPORT\n")
            f.write("=" * 60 + "\n")
            f.write("Generated by GPT-4 Analysis\n\n")
            f.write(analysis_result)
        print(f"✅ Analysis report saved to {filename}")
    except Exception as e:
        print(f"❌ Error saving report: {e}")

def display_analysis_results(analysis_result):
    """Display the analysis results in a formatted way"""
    print("\n" + "=" * 80)
    print("🤖 GPT-4 COMPREHENSIVE REVIEW ANALYSIS")
    print("=" * 80)
    # Split the analysis into sections for better readability
    for section in filter(str.strip, analysis_result.split('\n\n')):
        print(section)
        print("-" * 60)
    print("\n✅ Analysis complete!")

def export_to_excel(analysis_data, file_path):
    """Export all data and analysis to Excel file"""
    try:
        print(f"\n📊 Exporting data to Excel: {file_path}")

        # Check if analysis_data has the expected structure
        if isinstance(analysis_data, dict) and 'cluster_reviews' in analysis_data and 'analysis_result' in analysis_data:
            cluster_reviews = analysis_data['cluster_reviews']
            analysis_result = analysis_data['analysis_result']
        else:
            # If it's just the analysis text, create a simple export
            with pd.ExcelWriter(file_path, engine='openpyxl') as writer:
                pd.DataFrame({'Analysis': [str(analysis_data)]}).to_excel(writer, sheet_name='Analysis_Report', index=False)
            print(f"✅ Analysis exported to '{file_path}'")
            return True

        with pd.ExcelWriter(file_path, engine='openpyxl') as writer:
            # Sheet 1: Review Summary
            if cluster_reviews:
                review_data = [
                    {
                        'Product': product,
                        'Cluster': cluster,
                        'Customer_Type': review_data_item.get('cluster_info', {}).get('customer_type', 'N/A'),
                        'Age': review_data_item.get('cluster_info', {}).get('avg_age', 'N/A'),
                        'Gender': review_data_item.get('cluster_info', {}).get('dominant_gender', 'N/A'),
                        'Occupation': review_data_item.get('cluster_info', {}).get('dominant_occupation', 'N/A'),
                        'Income': review_data_item.get('cluster_info', {}).get('dominant_income', 'N/A'),
                        'Review': review_data_item.get('review', 'N/A')
                    }
                    for product, reviews in cluster_reviews.items()
                    for cluster, review_data_item in reviews.items()
                ]
                pd.DataFrame(review_data).to_excel(writer, sheet_name='Reviews', index=False)

                # Sheet 2: Ratings Data
                ratings_data = []
                for product, reviews in cluster_reviews.items():
                    for cluster, review_data_item in reviews.items():
                        review_text = review_data_item.get('review', '')
                        rating_row = {'Product': product, 'Cluster': cluster}
                        for metric in RATING_METRICS:
                            try:
                                rating = int(review_text.split(f"{metric}: ")[1][0])
                                rating_row[metric] = rating
                            except Exception:
                                rating_row[metric] = None
                        ratings_data.append(rating_row)
                pd.DataFrame(ratings_data).to_excel(writer, sheet_name='Ratings', index=False)

            # Sheet 3: Analysis Report
            pd.DataFrame({'Analysis': [analysis_result]}).to_excel(writer, sheet_name='GPT4_Analysis', index=False)

        print(f"✅ Data exported to '{file_path}'")
        return True

    except Exception as e:
        print(f"❌ Error exporting to Excel: {e}")
        return False

# Alternative function for backward compatibility
def export_to_excel_legacy(cluster_reviews, analysis_result, file_path=None):
    """Legacy export function - wraps the new function"""
    if file_path is None:
        file_path = EXCEL_EXPORT_FILENAME
    
    analysis_data = {
        'cluster_reviews': cluster_reviews,
        'analysis_result': analysis_result
    }
    
    return export_to_excel(analysis_data, file_path)